data:
  input_path: /home/galucia/Lithium4/preparation/output/PbPb/correlation_PbPb_hadronpid.root
  suffix: PbPb
  selection: Default

input_models_path: /home/galucia/Lithium4/femto/models/lambda_models_LL_10.root

centrality_bins:
  - '010'
  - '1050'

fit_options:
  ground_state_only: false
  use_smoothening: true
  finer_binning: true
  lambda_to_one: false
  lambda_to_zero: false
  lambda_variation: 10
  match_ratio: false
  LL: true

available_bkgs:
  - nominal/hLambdaSigmaCorrectedCk_Smeared_nominal
  - nominal/hLambdaSigmaCorrectedCk_Smeared_nominal_higher
  - nominal/hLambdaSigmaCorrectedCk_Smeared_nominal_lower
  - upper/hLambdaSigmaCorrectedCk_Smeared_upper
  - upper/hLambdaSigmaCorrectedCk_Smeared_upper_higher
  - upper/hLambdaSigmaCorrectedCk_Smeared_upper_lower
  - lower/hLambdaSigmaCorrectedCk_Smeared_lower
  - lower/hLambdaSigmaCorrectedCk_Smeared_lower_higher
  - lower/hLambdaSigmaCorrectedCk_Smeared_lower_lower

available_signals:
  - hCkHist
  - hCkHist_SigmaUp
  - hCkHist_SigmaDown

available_model_param_variations:
  - aRe_1s0_up/hLambdaSigmaCorrectedCk_Smeared_aRe_1s0_up
  - aRe_1s0_down/hLambdaSigmaCorrectedCk_Smeared_aRe_1s0_down
  - r_1s0_up/hLambdaSigmaCorrectedCk_Smeared_r_1s0_up
  - r_1s0_down/hLambdaSigmaCorrectedCk_Smeared_r_1s0_down
  - aRe_3s1_up/hLambdaSigmaCorrectedCk_Smeared_aRe_3s1_up
  - aRe_3s1_down/hLambdaSigmaCorrectedCk_Smeared_aRe_3s1_down
  - r_3s1_up/hLambdaSigmaCorrectedCk_Smeared_r_3s1_up
  - r_3s1_down/hLambdaSigmaCorrectedCk_Smeared_r_3s1_down

systematics_file: /home/galucia/Lithium4/preparation/output/PbPb/systematic_uncertainties.root