# configs/lambda_models_010.yaml
lambda_modification_factor: 0.1
lambda_variation: 0.10

centrality_bins:
  - '010'
  - '1050'

paths:
  lambda_parameters: /home/galucia/Lithium4/calibration/output/lambda_parameters.root
  resolution: /data/galucia/lithium/MC/AnalysisResults_LHC25g11.root
  mixed_event_reference: /home/galucia/Lithium4/preparation/output/PbPb/LHC25_PbPb_pass1_hadronpid_event_mixing.root
  output_model: /home/galucia/Lithium4/femto/models/lambda_models_coulomb_10.root

ck_input:
  root_file: /home/galucia/phemto/output/pHe3_coulomb_rescaled.root
  centralities:
    '010': hcats_CF_r=6.12_fm
    '1050': hcats_CF_r=4.90_fm
  
sigma_ck_input:
  root_file: /home/galucia/phemto/output/he3Sigma_recomputed_rescaled.root
  centralities:
    '010': hhe3_Sigma_plus_CF_r=6.12_fm
    '1050': hhe3_Sigma_plus_CF_r=4.90_fm
  