#
# Configuration file for plots
#

outPath: /home/galucia/Lithium4/figures/figures_for_forum/figures.root

plots:
  [

    # correlation function - antimatter - cent 0-10% - 23 + 24
    {
      axisSpecs: 
        [
          # x axis
          {
            nbins: 100,
            xmin: 0.,
            xmax: 0.405,
            name: 'antimatter_010',
            title: '; #it{k}* (GeV/#it{c}); C(#it{k}*)',
          },
          # y axis
          {
            nbins: 0,
            xmin: 0.,
            xmax: 1.4,
            name: 'antimatter_010',
            title: '; #it{k}* (GeV/#it{c}); C(#it{k}*)',
          },
        ],
      canvas:
        {
          logy: False,
          left_margin: 0.15,
        },
      hists:
        [
          {
            inPath: /home/galucia/Lithium4/preparation/checks/correlation_hadronpid_pass1_pass4_reject_multiples.root,
            histName: CorrelationAntimatter/Default/hCorrelation010,
            histLabel: '#bar{p}-^{3}#bar{He}, 0-10%',
            kwargs: {
                      line_color: 797, line_width: 1, line_style: 1,
                      marker_color: 797, marker_style: 20, marker_size: 1,
                      draw_option: 'p e0 same',
                      leg_option: 'p',
                    }
          },
        ],
      lines:
        [
          {
            lineSpecs: {
                        x1: 0.081,
                        x2: 0.081,
                        y1: 0.,
                        y2: 1.4,
                        name: '^{4}Li, #it{k}* = 0.081 GeV/#it{c}'
                      },
            kwargs: {
                      line_color: 632, # kRed+2
                      line_width: 2,
                      line_style: 2,
                    }
          },
          {
            lineSpecs: {
                        x1: 0.0,
                        x2: 0.405,
                        y1: 1.,
                        y2: 1.,
                        name: 'No interaction'
                      },
            kwargs: {
                      line_color: 16, # Gray
                      line_width: 2,
                      line_style: 2,
                    }
          },
        ],
      legends:
        [
          {
          bool: 1,
          xmin: 0.54, xmax: 0.88,
          ymin: 0.27, ymax: 0.52,
          kwargs: {
                    border_size: 0, nColumns: 1, textSize: 600,
                    fill_color: 0, draw_option: 'same',
                  }
          },
        ],
      outPDF:  /home/galucia/Lithium4/figures/figures_for_forum/antimatter_010.pdf
    },

    # correlation function - matter - cent 0-10% - 23 + 24
    {
      axisSpecs: 
        [
          # x axis
          {
            nbins: 100,
            xmin: 0.,
            xmax: 0.405,
            name: 'matter_010',
            title: '; #it{k}* (GeV/#it{c}); C(#it{k}*)',
          },
          # y axis
          {
            nbins: 0,
            xmin: 0.,
            xmax: 1.4,
            name: 'matter_010',
            title: '; #it{k}* (GeV/#it{c}); C(#it{k}*)',
          },
        ],
      canvas:
        {
          logy: False,
          left_margin: 0.15,
        },
      hists:
        [
          {
            inPath: /home/galucia/Lithium4/preparation/checks/correlation_hadronpid_pass1_pass4_reject_multiples.root,
            histName: CorrelationMatter/Default/hCorrelation010,
            histLabel: 'p-^{3}He, 0-10%',
            kwargs: {
                      line_color: 797, line_width: 1, line_style: 1,
                      marker_color: 797, marker_style: 20, marker_size: 1,
                      draw_option: 'p e0 same',
                      leg_option: 'p',
                    }
          },
        ],
      lines:
        [
          {
            lineSpecs: {
                        x1: 0.081,
                        x2: 0.081,
                        y1: 0.,
                        y2: 1.4,
                        name: '^{4}Li, #it{k}* = 0.081 GeV/#it{c}'
                      },
            kwargs: {
                      line_color: 632, # kRed+2
                      line_width: 2,
                      line_style: 2,
                    }
          },
          {
            lineSpecs: {
                        x1: 0.0,
                        x2: 0.405,
                        y1: 1.,
                        y2: 1.,
                        name: 'No interaction'
                      },
            kwargs: {
                      line_color: 16, # Gray
                      line_width: 2,
                      line_style: 2,
                    }
          },
        ],
      legends:
        [
          {
          bool: 1,
          xmin: 0.54, xmax: 0.88,
          ymin: 0.27, ymax: 0.52,
          kwargs: {
                    border_size: 0, nColumns: 1, textSize: 600,
                    fill_color: 0, draw_option: 'same',
                  }
          },
        ],
      outPDF:  /home/galucia/Lithium4/figures/figures_for_forum/matter_010.pdf
    },


  ]