outPath: /home/galucia/Lithium4/preparation/checks/lambda_parameters.root

plots:
  [
    # Lambda parameters
    {
      axisSpecs: 
        [
          # x axis
          {
            nbins: 100,
            xmin: 0.,
            xmax: 0.40,
            name: 'lambda_parameters_0_10',
            title: 'FT0C Centrality 0-10%; #it{k}* (GeV/#it{c}); #lambda_{p ^{3}He}',
          },
          # y axis
          {
            nbins: 0,
            xmin: 0.45,
            xmax: 1.05,
            name: 'lambda_parameters_0_10',
            title: 'FT0C Centrality 0-10%; #it{k}* (GeV/#it{c}); #lambda_{p ^{3}He}',
          },
        ],
      canvas:
        {
          logy: False,
          left_margin: 0.15,
        },
      hists:
        [
          {
            inPath: /home/galucia/Lithium4/calibration/output/lambda_parameters.root,
            histName: centrality_0_10/Antimatter/hLambdaParameters,
            histLabel: '#bar{p} + ^{3}#bar{He}',
            kwargs: {
                      line_color: 797, line_width: 1, line_style: 1,
                      marker_color: 797, marker_style: 20, marker_size: 1,
                      draw_option: 'p hist same',
                      leg_option: 'p',
                    }
          },
          {
            inPath: /home/galucia/Lithium4/calibration/output/lambda_parameters.root,
            histName: centrality_0_10/Matter/hLambdaParameters,
            histLabel: 'p + ^{3}He',
            kwargs: {
                      line_color: 601, line_width: 1, line_style: 1,
                      marker_color: 601, marker_style: 20, marker_size: 1,
                      draw_option: 'p hist same',
                      leg_option: 'p',
                    }
          },
          {
            inPath: /home/galucia/Lithium4/calibration/output/lambda_parameters.root,
            histName: centrality_0_10/Both/hLambdaParameters,
            histLabel: 'p + ^{3}He #oplus #bar{p} + ^{3}#bar{He}',
            kwargs: {
                      line_color: 428, line_width: 1, line_style: 1,
                      marker_color: 428, marker_style: 20, marker_size: 1,
                      draw_option: 'p hist same',
                      leg_option: 'p',
                    }
          },
        ],
      legends:
        [
          {
          bool: 1,
          xmin: 0.52, xmax: 0.82,
          ymin: 0.17, ymax: 0.42,
          kwargs: {
                    border_size: 0, nColumns: 1, textSize: 520,
                    fill_color: 0, draw_option: 'same',
                  }
          },
        ],
      outPDF:  /home/galucia/Lithium4/calibration/figures/lambda_parameters_0_10.pdf
    },

    {
      axisSpecs: 
        [
          # x axis
          {
            nbins: 100,
            xmin: 0.,
            xmax: 0.40,
            name: 'lambda_parameters_10_50',
            title: 'FT0C Centrality 10-50%; #it{k}* (GeV/#it{c}); #lambda_{p ^{3}He}',
          },
          # y axis
          {
            nbins: 0,
            xmin: 0.45,
            xmax: 1.05,
            name: 'lambda_parameters_10_50',
            title: 'FT0C Centrality 10-50%; #it{k}* (GeV/#it{c}); #lambda_{p ^{3}He}',
          },
        ],
      canvas:
        {
          logy: False,
          left_margin: 0.15,
        },
      hists:
        [
          {
            inPath: /home/galucia/Lithium4/calibration/output/lambda_parameters.root,
            histName: centrality_10_50/Antimatter/hLambdaParameters,
            histLabel: '#bar{p} + ^{3}#bar{He}',
            kwargs: {
                      line_color: 797, line_width: 1, line_style: 1,
                      marker_color: 797, marker_style: 20, marker_size: 1,
                      draw_option: 'p hist same',
                      leg_option: 'p',
                    }
          },
          {
            inPath: /home/galucia/Lithium4/calibration/output/lambda_parameters.root,
            histName: centrality_10_50/Matter/hLambdaParameters,
            histLabel: 'p + ^{3}He',
            kwargs: {
                      line_color: 601, line_width: 1, line_style: 1,
                      marker_color: 601, marker_style: 20, marker_size: 1,
                      draw_option: 'p hist same',
                      leg_option: 'p',
                    }
          },
          {
            inPath: /home/galucia/Lithium4/calibration/output/lambda_parameters.root,
            histName: centrality_10_50/Both/hLambdaParameters,
            histLabel: 'p + ^{3}He #oplus #bar{p} + ^{3}#bar{He}',
            kwargs: {
                      line_color: 428, line_width: 1, line_style: 1,
                      marker_color: 428, marker_style: 20, marker_size: 1,
                      draw_option: 'p hist same',
                      leg_option: 'p',
                    }
          },
        ],
      legends:
        [
          {
          bool: 1,
          xmin: 0.52, xmax: 0.52,
          ymin: 0.17, ymax: 0.42,
          kwargs: {
                    border_size: 0, nColumns: 1, textSize: 520,
                    fill_color: 0, draw_option: 'same',
                  }
          },
        ],
      outPDF:  /home/galucia/Lithium4/calibration/figures/lambda_parameters_10_50.pdf
    },

    {
      axisSpecs: 
        [
          # x axis
          {
            nbins: 100,
            xmin: 0.,
            xmax: 0.40,
            name: 'lambda_parameters_all',
            title: '; #it{k}* (GeV/#it{c}); #lambda',
          },
          # y axis
          {
            nbins: 0,
            xmin: 0.0005,
            xmax: 1.05,
            name: 'lambda_parameters_all',
            title: '; #it{k}* (GeV/#it{c}); #lambda',
          },
        ],
      canvas:
        {
          logy: True,
          left_margin: 0.15,
        },
      hists:
        [
          {
            inPath: /home/galucia/Lithium4/calibration/output/lambda_parameters.root,
            histName: centrality_0_10/Both/hLambdaParameters,
            histLabel: '#lambda_{p - ^{3}He} (0-10%)',
            kwargs: {
                      line_color: 601, line_width: 1, line_style: 1,
                      marker_color: 601, marker_style: 20, marker_size: 1,
                      draw_option: 'p hist same',
                      leg_option: 'p',
                    }
          },
          {
            inPath: /home/galucia/Lithium4/calibration/output/lambda_parameters.root,
            histName: centrality_0_10/Both/hLambdaSigmaParameters,
            histLabel: '#lambda_{p #leftarrow #Sigma - ^{3}He} (0-10%)',
            kwargs: {
                      line_color: 797, line_width: 1, line_style: 1,
                      marker_color: 797, marker_style: 20, marker_size: 1,
                      draw_option: 'p hist same',
                      leg_option: 'p',
                    }
          },

          {
            inPath: /home/galucia/Lithium4/calibration/output/lambda_parameters.root,
            histName: centrality_10_50/Both/hLambdaParameters,
            histLabel: '#lambda_{p - ^{3}He} (10-50%)',
            kwargs: {
                      line_color: 601, line_width: 1, line_style: 1,
                      marker_color: 601, marker_style: 24, marker_size: 1,
                      draw_option: 'p hist same',
                      leg_option: 'p',
                    }
          },
          {
            inPath: /home/galucia/Lithium4/calibration/output/lambda_parameters.root,
            histName: centrality_10_50/Both/hLambdaSigmaParameters,
            histLabel: '#lambda_{p #leftarrow #Sigma - ^{3}He} (10-50%)',
            kwargs: {
                      line_color: 797, line_width: 1, line_style: 1,
                      marker_color: 797, marker_style: 24, marker_size: 1,
                      draw_option: 'p hist same',
                      leg_option: 'p',
                    }
          },
        ],
      legends:
        [
          {
          bool: 1,
          xmin: 0.32, xmax: 0.82,
          ymin: 0.17, ymax: 0.42,
          kwargs: {
                    border_size: 0, nColumns: 2, textSize: 520,
                    fill_color: 0, draw_option: 'same',
                  }
          },
        ],
      outPDF:  /home/galucia/Lithium4/calibration/figures/lambda_parameters_all.pdf
    },
]